### ISSUE TITLE
Intermitten failure when running cucumber

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/LocalSupport#150]
I intermittently get the following error/stack trace when running cucumber:

cucumber features/admin/admin_moderate_proposed_organisations.feature
WARNING: Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.0
method `respond_to?' called on unexpected T_NODE object (0x007fab25d3e438 flags=0x1b3011c) (NotImplementedError)
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:95:in `=='
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:95:in `New'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:95:in `block (2 levels) in eval'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/error.rb:84:in `block in try'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/error.rb:83:in `call'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/error.rb:83:in `TryCatch'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/error.rb:83:in `try'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:95:in `block in eval'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:248:in `block (2 levels) in lock_scope_and_enter'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:245:in `call'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:245:in `HandleScope'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:245:in `block in lock_scope_and_enter'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:244:in `call'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:244:in `Locker'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:244:in `lock_scope_and_enter'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:204:in `enter'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/therubyracer-0.12.1/lib/v8/context.rb:94:in `eval'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/commonjs-0.2.7/lib/commonjs/environment.rb:16:in `require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/less-2.5.1/lib/less/loader.rb:28:in `require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/less-2.5.1/lib/less.rb:15:in `<module:Less>'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/less-2.5.1/lib/less.rb:9:in `<top (required)>'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/less-rails-2.5.0/lib/less/rails.rb:6:in `<top (required)>'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/less-rails-2.5.0/lib/less-rails.rb:1:in `<top (required)>'
/Users/michael/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `each'
/Users/michael/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `block in require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
/Users/michael/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
/Users/michael/Desktop/LocalSupport/config/application.rb:9:in `<top (required)>'
/Users/michael/Desktop/LocalSupport/config/environment.rb:2:in `require'
/Users/michael/Desktop/LocalSupport/config/environment.rb:2:in `<top (required)>'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-rails-1.4.2/lib/cucumber/rails.rb:7:in `require'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-rails-1.4.2/lib/cucumber/rails.rb:7:in `<top (required)>'
/Users/michael/Desktop/LocalSupport/features/support/env.rb:11:in `require'
/Users/michael/Desktop/LocalSupport/features/support/env.rb:11:in `<top (required)>'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/lib/cucumber/rb_support/rb_language.rb:95:in `load'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:82:in `each'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:42:in `run!'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/gems/cucumber-1.3.19/bin/cucumber:13:in `<top (required)>'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/bin/cucumber:23:in `load'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/bin/cucumber:23:in `<main>'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
/Users/michael/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'

**Comment by mtc2013** [comment]
I seem to have fixed this issue by installing the latest therubyracer and then bundle updating.

**Comment by tansaku** [comment]
https://www.youtube.com/watch?v=Z4A6uhRm4fI
