### ISSUE TITLE
Geocoder log messages polluting the test runs

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/LocalSupport#160]
`Geocoder: HTTP request being made for http://maps.googleapis.com/maps/api/geocode/json?address=64+pinner+road%2C+HA1+3TE&language=en&sensor=false`

appearing a lot in both cucumber and rspec runs all of a sudden

**Comment by tansaku** [comment]
might be related to upgrade to bundler upgrading the geocoder gem ...

**Comment by nisevi** [comment]
Hi there @tansaku, is this issue related to a task somewhere to start looking around?

**Comment by tansaku** [comment]
hi @nisevi careful with issues in here opened over 2 years ago - might not be relevant - I recommend working against our tracker: https://www.pivotaltracker.com/n/projects/742821
