### ISSUE TITLE
Manual Installation (the long way) 

### ISSUE THREAD

**Issue by SergiosLen** [AgileVentures/LocalSupport#186]
I have done the install in my Ubuntu 14.04 laptop and I had those problems:

Until 8 no problem at first but:
1. Run bundle install to get the gems <== _I had to install bundle **gem install bundle**_
2. Run bower install to get the javascript dependencies <== _I had to install bower and to do so_ 
- $ **npm config set prefix /usr/local**
- $ **npm install -g bower**

> I followed this http://stackoverflow.com/questions/12369390/bower-command-not-found 

And then on 11 I found out that I had problems with postgresql.
I figured out that I had to stop the server through 
- sudo sysv-rc-conf <== _The only way I was able to  do it_
  
  then uninstall everything
- sudo apt-get --purge remove postgresql* 

and finaly fresh install
- sudo apt-get install postgresql 

After that everything worked fine.
I don't know if that is usefull to someone else.

**Comment by johnnymo87** [comment]
Do you happen to still have the error messages for postgresql that prompted you to do this re-install?

**Comment by SergiosLen** [comment]
No everything is ok after that. It seems that Ubuntu comes with an installation of postgresql and that was the problem. 
(_Sorry for the late respond I was out the weekend_)

**Comment by enkanba** [comment]
Was installing lately in Ubuntu 16.04.  for npm to run I had to do the following:
`ln -s /usr/bin/nodejs /usr/bin/node`
