### ISSUE TITLE
Issue with capybara-webkit - my experience

### ISSUE THREAD

**Issue by Proskurina** [AgileVentures/LocalSupport#204]
System: OS X 10.11 - El Capitan
Ruby: ruby 2.0.0 
capybara: 2.4.1
capybara-webkit: 1.6.0

I had an issue with capybara-webkit.
When I was running `bundle exec rake cucumber` 25 tests were failing, all with the same error `/Users/yana/.rvm/gems/ruby-2.0.0-p643/gems/capybara-webkit-1.6.0/bin/webkit_server failed to start. (Capybara::Webkit::ConnectionError)` 

I tried this (as advised here https://github.com/thoughtbot/capybara-webkit/issues/678):

```
gem uninstall capybara-webkit
brew install qt5
brew linkapps qt5
brew link --force qt5
gem install capybara-webkit
```

But I still had the same error.

Then I did `brew doctor`.

And one of the issues was:

```
Having additional scripts in your path can confuse software installed via Homebrew if the config script overrides a system or Homebrew provided script of the same name.
```

I checked where my `qmake` was and it was not in the right place.

So, I removed several paths from my $PATH, and did

```
gem uninstall capybara-webkit
brew uninstall qt5
brew install qt5
brew linkapps qt5
brew link --force qt5
gem install capybara-webkit
```

Then I checked that qmake was in the right place: 

```
which qmake

/usr/local/bin/qmake

```

Now all tests pass.

**Comment by johnnymo87** [comment]
Thank you for documenting this!

**Comment by tansaku** [comment]
@johnnymo87 @Proskurina I guess we should get this moved into the installation wiki ...?

**Comment by nisevi** [comment]
@tansaku I updated the [wiki](https://github.com/AgileVentures/LocalSupport/wiki/OSX-installation) with this issue, please take a look and tell me if you would like to change something, since I don't have a mac and the steps I wrote are based on the given description to solve it :+1: .
