### ISSUE TITLE
Deprecated Airbrake.blacklist_keys

### ISSUE THREAD

**Issue by bryszard** [AgileVentures/LocalSupport#293]
I get deprecation warning about this especially in heroku. 

When I search for this in the repo I find this:

![image](https://cloud.githubusercontent.com/assets/12682792/14795895/f09aacc8-0b2a-11e6-8b10-2c06965bff38.png)

**Comment by tansaku** [comment]
hmm airbrake gem of config will need an upgrade - however we should add this as a chore to pivotal tracker
