### ISSUE TITLE
Custom bundle exec rake db:setup doesn't work

### ISSUE THREAD

**Issue by bryszard** [AgileVentures/LocalSupport#294]
Configuring LS on heroku I've found that our custom rake db:setup doesn't work. Default doesn't work either.

Problem with default db:setup is that it breakes:
![problem with db setup 2](https://cloud.githubusercontent.com/assets/12682792/14812443/90f879b2-0b9d-11e6-947b-23b2dee0b691.PNG)

The reason of that is that in db:seeds there is part about Feature model update, but default db:setup doesn't create Features - they are created in migrations, and db:setup does db:schema:load instead of db:migrate. A proof:

![problem with db setup](https://cloud.githubusercontent.com/assets/12682792/14812521/cf93c366-0b9d-11e6-998f-f3dc74268ecb.PNG)

Probably someone tried to address this problem, because there is a file /lib/tasks/setup.rake, which contains this:

![custom db setup](https://cloud.githubusercontent.com/assets/12682792/14812550/f3d6e8e8-0b9d-11e6-9321-8110b0817f04.PNG)

It seems though that this custom db:setup doesn't overwrite the default one.

**Comment by tansaku** [comment]
good catch @bryszard - I wonder if this is what is breaking our automated deploys ... looks like we need to investigate how to ensure the custom db:setup overrides the default one

**Comment by Maroo-b** [comment]
@tansaku the easiest solution is to rename the task I changed it from **setup** to **custom_setup** I attached a PR https://github.com/AgileVentures/LocalSupport/pull/303

**Comment by nisevi** [comment]
Hey @tansaku this issue was solved by merging this https://github.com/AgileVentures/LocalSupport/commit/fc0c3dbf4686203bd87182f47ae178a97cc44e91 right? I think that we can close it now.

**Comment by tansaku** [comment]
@nisevi very possibly ...
