### ISSUE TITLE
Devise failing hard prevents configuration of heroku

### ISSUE THREAD

**Issue by bryszard** [AgileVentures/LocalSupport#296]
I was setting up the LS on Heroku, but when I was switching to the new branch a Devise error was being thrown:

![image](https://cloud.githubusercontent.com/assets/12682792/14812845/3ab85fb6-0b9f-11e6-9d67-d5e5ca4281b5.png)

I've found out that there was a commit to the /config/initializers/devise.rb file which put there a hard failing rescue if secret_key is not set on production. What is strange for me - the error is being thrown in the code before the secret_key is set. I'm not sure if that's on purpose:

![image](https://cloud.githubusercontent.com/assets/12682792/14812890/78a5e0d2-0b9f-11e6-8fe3-fff449c422eb.png)

Any way, I had to comment out the error part of devise.rb to be able to set the app on Heroku.

**Comment by Maroo-b** [comment]
@bryszard You have to set the ENV variable `DEVISE_SECRET_KEY` from Heroku Dashboard otherwise some links for invitation or confirmation won't work after server restart. The above exception was raised to fix this issue https://www.pivotaltracker.com/story/show/115398997

**Comment by bryszard** [comment]
@marouen, so maybe you should add some information how to do that in the
Local Support's Wiki? (
https://github.com/AgileVentures/LocalSupport/wiki/Deploying-to-Heroku) It
would save me 2 hours of work ;).

2016-04-28 10:15 GMT+02:00 Marouen Bousnina <notifications@github.com>:

**Comment by Maroo-b** [comment]
@bryszard good idea, we should check the existent documentations and update it ( I remember that there is a ticket in Pivotal Tracker)

**Comment by nisevi** [comment]
Comment was added to the wiki.
