### ISSUE TITLE
selenium install on C9 fails

### ISSUE THREAD

**Issue by enkanba** [AgileVentures/LocalSupport#378]
`downloading http://selenium.googlecode.com/files/selenium-server-2.37.0.zip... /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:359:in`open_http': 404 Not Found (OpenURI::HTTPError)`

The URI is indeed comes back with response 404.

**Comment by enkanba** [comment]
Workaround: https://github.com/shvets/selenium/pull/3

**Comment by tansaku** [comment]
thanks for this @enkanba - I've just updated the c9 docs in relation to this ...
