### ISSUE TITLE
Issue with getting LocalSupport set up on my machine; psql-related?

### ISSUE THREAD

**Issue by VincentLu91** [AgileVentures/LocalSupport#386]
Taken from Slack #localsupport channel:

I’m in the middle of trying to install the localsupport project on my computer. I’m on the last step now, but I couldn’t get the DB created. I ran rake db:create, and I got this:

could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in`new'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in`initialize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in`postgresql_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in`checkout_new_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in`block in checkout'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in`checkout'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in`mon_synchronize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in`retrieve_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_handling.rb:87:in`connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/postgresql_database_tasks.rb:15:in`create'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:93:in `create'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:107:in`block in create_current'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in`each'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:106:in`create_current'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:248:in`block in execute'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in`execute'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/airbrake-5.4.4/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:187:in`block in invoke_with_call_chain'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:180:in`invoke_with_call_chain'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:152:in`invoke_task'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in`each'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:117:in`run_with_threads'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:80:in`block in run'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:77:in`run'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/bin/rake:23:in`load'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/bin/rake:23:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"ls_development", "pool"=>5, "username"=>"postgres", "password"=>nil}
could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in`initialize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in`connect'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in`new'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in`new_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in`acquire_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in`mon_synchronize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in`block in connection'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in`connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_handling.rb:113:in`retrieve_connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/connection_handling.rb:87:in `connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/postgresql_database_tasks.rb:6:in`connection'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:93:in`create'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:276:in`block in each_current_configuration'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in`each_current_configuration'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:17:in`block (2 levels) in <top (required)>'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in`each'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/airbrake-5.4.4/lib/airbrake/rake/task_ext.rb:19:in`execute'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in`mon_synchronize'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:173:in`invoke'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in`block (2 levels) in top_level'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in`block in top_level'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:102:in`top_level'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:178:in`standard_exception_handling'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/Users/Vincent/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in`<top (required)>'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/bin/rake:23:in `load'
/Users/Vincent/.rvm/rubies/ruby-2.3.1/bin/rake:23:in`<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"ls_test", "pool"=>5, "username"=>"postgres", "password"=>nil}

I'm using OS X 10.10.5. There could be an issue with the postgressql install. 

I ran 
`sudo apt-get install postgresql`
and I got this after providing the password I got this:
`sudo: apt-get: command not found`

**Comment by johnnymo87** [comment]
It sounds like you don't have postgres installed. I think [Postgres.app](http://postgresapp.com/) is the easiest way to install postgres on a mac.

**Comment by VincentLu91** [comment]
Thanks @johnnymo87 I managed to get it installed and LocalSupport is working. I'm looking forward to an upcoming session!

**Comment by johnnymo87** [comment]
Awesome! Join us in the `LocalSupport` channel in slack to find opportunities to pair up and stories to work on.
