### ISSUE TITLE
The 'Pair with me' badge displays unnormal.

### ISSUE THREAD

**Issue by kenshinji** [AgileVentures/LocalSupport#433]
![issue](https://cloud.githubusercontent.com/assets/1403893/24362903/c9e59448-1340-11e7-927b-645891a31b95.png)

I think I can fix this issue. Because I have this badge on one of my repositories, and it displays nomarlly.

**Comment by tansaku** [comment]
@kenshinji - I just had a go at this - couldn't immediately fix it https://meta.stackexchange.com/questions/38915/creating-an-image-link-in-markdown-format I'm wondering if the github markdown format changed.

In the four years I've had it there I don't think anyone has emailed me through it, so I thought maybe just remove it until we can come up with another fix ...

**Comment by kenshinji** [comment]
@tansaku I have the badge in one of my repositories [here](https://github.com/kenshinji/CodilitySolutions), it works. I use a html tag to display it though.
`<a href="mailto:gundam0083ster@gmail.com" title="Pair program with me!">
  <img  src="http://pairprogramwith.me/badge.png"
        alt="Pair program with me!" />
</a>`
Shall we approach it the markdown way?

**Comment by tansaku** [comment]
@kenshinji sounds great - let's do it!
